#!/bin/sh

# cleanup
rm -rf obj_dir
rm -f *.vcd

# run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace all.sv clktick.sv f1_fsm.sv lfsr.sv mux.sv delay.sv --exe delay_tb.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vall.mk Vall

# run executable simulation file
echo "\nRunning simulation"
obj_dir/Vall
echo "\nSimulation completed"

